treechopped1: #hybrid
	Defaults:
		UseTilesetExtension: true
		ZOffset: -2024
	make: tree1anim
		Length: *
		Tick: 80
	idle: tree1shop
		Start: 0
	damaged-idle: tree1shop
		Start: 1
	crippled-idle: tree1shop
		Start: 2
    
treechopped2:
	Defaults:
		UseTilesetExtension: true
		ZOffset: -2024
	make: tree2anim
		Length: *
		Tick: 80
	idle: tree2shop
		Start: 0
	damaged-idle: tree2shop
		Start: 1
	crippled-idle: tree2shop
		Start: 2
    
treechopped3:
	Defaults:
		UseTilesetExtension: true
		ZOffset: -2024
	make: tree3anim
		Length: *
		Tick: 80
	idle: tree3shop
		Start: 0
	damaged-idle: tree3shop
		Start: 1
	crippled-idle: tree3shop
		Start: 2
        
treechopped4:
	Defaults:
		UseTilesetExtension: true
		ZOffset: -2024
	make: tree4anim
		Length: *
		Tick: 80
	idle: tree4shop
		Start: 0
	damaged-idle: tree4shop
		Start: 1
	crippled-idle: tree4shop
		Start: 2

deerstand:
	Defaults:
		Offset: 0,-12
		TilesetOverrides:
			DESERT: TEMPERAT
			WINTER: TEMPERAT
			SNOW: TEMPERAT
	idle: 
		Start: 0
	idle2: 
		Start: 1
	corputed1:
		Start: 2
	corputed2:
		Start: 3
	empty: ironore4
		Start: 9 
		
coppermine:
	Defaults:
		Offset: 0,-5
		TilesetOverrides:
			DESERT: TEMPERAT
	active: cropmin
		Length: *
		Tick: 80
		Start: 0
	idle: cropmin
		Start: 0
		
mwlumbershack:
	Defaults:
		TilesetOverrides:
			DESERT: TEMPERAT
	idle: mwlumbershack
		Start: 0
		Offset: 0,-12,0
		
ironmine:
	Defaults:
		TilesetOverrides:
			DESERT: TEMPERAT
	active: iromin
		Length: 29
		Tick: 100
		Start: 1
	idle: iromin
		Start: 0
goldmine:
	Defaults:
		TilesetOverrides:
			DESERT: TEMPERAT
	active: golmin
		Length: 29
		Tick: 100
		Start: 1
	idle: golmin
		Start: 0

		
mwcamel:
	stand: mwcamel
		Start: 122
		Facings: 8
	run: mwcamel
		Start: 0
		Length: 8
		Facings: 8
		Tick: 100
	shoot: mwcamel
		Tick: 100
		Start: 66
		Length: 7
		Facings: 8
	die1: mwcamel
		Start: 132
		Length: 13
		Tick: 120
	# Burn
	die2: burninghorse
		Start: 76
		Length: 14
		Tick: 80
	idle1: mwcamel
		Tick: 100
		Start: 150
		Length: 7
		Facings: 8
	idle2: mwcamel
		Tick: 500
		Start: 206
		Length: 7
		Facings: 8
		
mwcameltrader:
	stand: 
		Start: 146
		Facings: 8
	run: 
		Start: 0
		Length: 8
		Facings: 8
		Tick: 100
	attack: 
		Start: 65
		Length: 8
		Facings: 8
		Tick: 80
	die1: 
		Start: 156
		Length: 15
		Tick: 80
	# large hit
	die2: splatterdead
		Length: *
		Tick: 80
	# poision
	die3: 
		Start: 187
		Length: 15
		Tick: 80
	# ballista
	die4: 
		Start: 203
		Length: 11
		Tick: 80
	die-crushed: e1rot
		Start: 16
		Length: 4
		Tick: 1600
		ZOffset: -511
	die5: burningman
		Length: *
		Tick: 80
		