^ChoppedTree:
	Inherits@1: ^SpriteActor
	Tooltip:
		Name: Tree(Chopped)
		ShowOwnerRow: false
	RenderSprites:
		Palette: staticterrain
	Building:
		Footprint: x
		Dimensions: 1,1
	WithSpriteBody:
		StartSequence: make
	AppearsOnRadar:
	RadarColorFromTerrain:
		Terrain: Tree
	Armor:
		Type: Wood
	Targetable:
		TargetTypes: Trees, NoAutoTarget, Choptree
	HiddenUnderShroud:
	ScriptTriggers:
	Health:
		HP: 150000
	HitShape:
	EditorTilesetFilter:
		Categories: Tree
	SelfHealing@Killsslef:
		PercentageStep: -1
		Step: -0
		HealIfBelow: 110
		Delay: 75
		DamageTypes: DefaultDeath
	WithPermanentInjury:
        TriggeringDamageStage: Critical
        InjuredSequencePrefix: crippled-
	WithMakeAnimation:

ChoppedtreeN1: #hybrid
	Inherits: ^ChoppedTree
	RenderSprites:
		Image: treechopped1
	LootableBody: 
		LootTypes: ChopTree
        
ChoppedtreeN2:
	Inherits: ^ChoppedTree
	RenderSprites:
		Image: treechopped2
	LootableBody: 
		LootTypes: ChopTree
        
ChoppedtreeN3:
	Inherits: ^ChoppedTree
	RenderSprites:
		Image: treechopped3
	Building:
		Footprint: _xx _x=
		Dimensions: 3,2
	LootableBody: 
		LootTypes: ChopTree
	EditorTilesetFilter:
		ExcludeTilesets: DESERT
        
ChoppedtreeN3A:
	Inherits: ^ChoppedTree
	RenderSprites:
		Image: treechopped3
	LootableBody: 
		LootTypes: ChopTree
        
ChoppedtreeN4:
	Inherits: ^ChoppedTree
	RenderSprites:
		Image: treechopped4
	LootableBody: 
		LootTypes: ChopTree

 
FIREPLACE:
	Inherits: ^Crate
	Crate:
		Lifetime: 240
	GiveCashCrateAction:
		Amount: 1000
		SelectionShares: 20
		UseCashTick: yes
	GiveUnitCrateAction@1:
		Units: e3newv2, e3newv2, e3newv2, e3newv2
		ValidFactions: Nod
	GiveUnitCrateAction@2:
		Units: e3new, e3new, e3new, e3new
		ValidFactions: GDI
	GiveUnitCrateAction@3:
		Units: dragonwalk
		Owner: Creeps
	GiveUnitCrateAction@4:
		Units: e2new, e2new
		ValidFactions: Nod
	GiveUnitCrateAction@5:
		Units: e2newv2, e2newv2
		ValidFactions: GDI
	GiveUnitCrateAction@6:
		Units: emptyross
	GiveUnitCrateAction@7:
		Units: ross4b
		ValidFactions: GDI
	GiveUnitCrateAction@8:
		Units: ross4c
		ValidFactions: Nod
	GiveMcvCrateAction:
		SelectionShares: 1
		Units: mcvnew
	ExplodeCrateAction:
		Weapon: LightningStrike
	RenderSprites:
		Image: fireplace
		Palette: ra
	WithSpriteBody:
		StartSequence: open
	Tooltip:
		Name: Campfire
		ShowOwnerRow: false
	WithIdleOverlay:
		Sequence: burnloop
		Palette: terrain
		