treechopped1: #hybrid
	Defaults:
		UseTilesetExtension: true
		ZOffset: -2024
	make: tree1anim
		Length: *
		Tick: 80
	idle: tree1shop
		Start: 0
	damaged-idle: tree1shop
		Start: 1
	crippled-idle: tree1shop
		Start: 2
        
stool1:
	idle: stoolmw
		Start: 0
deadstool1:
	idle: stoolmw
		Start: 8
stool2:
	idle: stoolmw
		Start: 1
deadstool2:
	idle: stoolmw
		Start: 9
stool3:
	idle: stoolmw
		Start: 2
deadstool3:
	idle: stoolmw
		Start: 10
stool4:
	idle: stoolmw
		Start: 3
deadstool4:
	idle: stoolmw
		Start: 11
stool5:
	idle: stoolmw
		Start: 4
deadstool5:
	idle: stoolmw
		Start: 12
stool6:
	idle: stoolmw
		Start: 5
deadstool6:
	idle: stoolmw
		Start: 13
stool7:
	idle: stoolmw
		Start: 6
deadstool7:
	idle: stoolmw
		Start: 14
stool8:
	idle: stoolmw
		Start: 7
deadstool8:
	idle: stoolmw
		Start: 15
        
table1:
	idle: tableroundmw
		Start: 0
deadtable1:
	idle: tableroundmw
		Start: 2
table2:
	idle: tableroundmw
		Start: 1
deadtable2:
	idle: tableroundmw
		Start: 3
table3:
	idle: itablesquare
		Start: 0
deadtable3:
	idle: itablesquare
		Start: 1
table4:
	idle: itablelongv
		Start: 0
deadtable4:
	idle: itablelongv
		Start: 1
table5:
	idle: itablelongs
		Start: 0
		Offset: 0,3
deadtable5:
	idle: itablelongs
		Start: 1
		Offset: 0,3
ichesta:
	idle: ichesta
		Start: 0
ichestdeada:
	idle: ichesta
		Start: 9
		make: *
ichestb:
	idle: ichestb
		Start: 0
ichestdeadb:
	idle: ichestb
		Start: 9
		make: *
ichestc:
	idle: ichestc
		Start: 0
ichestdeadc:
	idle: ichestc
		Start: 9
		make: *
        
        
ipaintinga:
	idle: ipainting
		Start: 0
ipaintingb:
	idle: ipainting
		Start: 1
ipaintingc:
	idle: ipainting
		Start: 2
ipaintingd:
	idle: ipainting
		Start: 3
        
barrelmw1:
	idle: barrelmw
		Start: 0
deadbarrelmw1:
	idle: barrelmw
		Start: 11
barrelmw2:
	idle: barrelmw
		Start: 1
deadbarrelmw2:
	idle: barrelmw
		Start: 12
barrelmw3:
	idle: barrelmw
		Start: 2
deadbarrelmw3:
	idle: barrelmw
		Start: 13
barrelmw4:
	idle: barrelmw
		Start: 3
deadbarrelmw4:
	idle: barrelmw
		Start: 14
barrelmw5:
	idle: barrelmw
		Start: 4
deadbarrelmw5:
	idle: barrelmw
		Start: 15
barrelmw6:
	idle: barrelmw
		Start: 5
deadbarrelmw6:
	idle: barrelmw
		Start: 16
barrelmw7:
	idle: barrelmw
		Start: 6
deadbarrelmw7:
	idle: barrelmw
		Start: 17
barrelmw8:
	idle: barrelmw
		Start: 7
deadbarrelmw8:
	idle: barrelmw
		Start: 18
barrelmw9:
	idle: barrelmw
		Start: 9
deadbarrelmw9:
	idle: barrelmw
		Start: 19
barrelmw10:
	idle: barrelmw
		Start: 10
deadbarrelmw10:
	idle: barrelmw
		Start: 20
barrelmw11:
	idle: barrelmw
		Start: 11
deadbarrelmw11:
	idle: barrelmw
		Start: 21
        
idoornorth:
	idle: idoorn
idoornorthopen:
	idle: idoorn
		Start: 9
		ZOffset: -1025
	make: idoorn
		Length: *
		Tick: 150
		ZOffset: -1025
idoorsouth:
	idle: idoors
idoorsouthopen:
	idle: idoors
		Start: 9
		ZOffset: -1025
	make: idoors
		Length: *
		Tick: 150
		ZOffset: -1025
idoorwest:
	idle: idoorw
		Offset: 6, -12
idoorwestopen:
	idle: idoorw
		Start: 9
		Offset: 6, -12
		ZOffset: -1025
	make: idoorw
		Length: *
		Tick: 150
		Offset: 6, -12
		ZOffset: -1025
idooreast:
	idle: idoore
		Offset: -6, -12
idooreastopen:
	idle: idoore
		Start: 9
		Offset: -6, -12
		ZOffset: -1025
	make: idoore
		Length: *
		Tick: 150
		Offset: -6, -12
		ZOffset: -1025
        
idoorsnorth:
	idle: idoorns
		Offset: -11,0
idoorsnorthopen:
	idle: idoorns
		Offset: -11,0
		Start: 9
		ZOffset: -1025
	make: idoorns
		Offset: -11,0
		Length: *
		Tick: 150
		ZOffset: -1025
idoorssouth:
	idle: idoorss
		Offset: -11,0
idoorssouthopen:
	idle: idoorss
		Offset: -11,0
		Start: 9
		ZOffset: -1025
	make: idoors
		Offset: -11,0
		Length: *
		Tick: 150
		ZOffset: -1025
idoorswest:
	idle: idoorws
		Offset: 6, -12
idoorswestopen:
	idle: idoorws
		Start: 9
		Offset: 6, -12
		ZOffset: -1025
	make: idoorws
		Length: *
		Tick: 150
		Offset: 6, -12
		ZOffset: -1025
idoorseast:
	idle: idoores
		Offset: -11, -12
idoorseastopen:
	idle: idoores
		Start: 9
		Offset: -11, -12
		ZOffset: -1025
	make: idoores
		Length: *
		Tick: 150
		Offset: -1, -12
		ZOffset: -1025
        
idooriron:
	idle: idoorgate
		ZOffset: 1025
idoorironopen:
	idle: idoorgate
		Start: 9
	make: idoorgate
		Length: *
		Tick: 150
		ZOffset: 1025
        
idoorbars:
	idle: idoorbarsdoor
		Offset: -11,6
idoorbarsopen:
	idle: idoorbarsdoor
		Offset: -11,6
		Start: 9
		ZOffset: -1025
	make: idoorbarsdoor
		Offset: -11,6
		Length: *
		Tick: 150
		ZOffset: -1025
        

switcha:
	idle: iswitcha
switchpulleda:
	idle: iswitcha
		Start: 5
	make: iswitcha
		Length: *
		Tick: 150
switchb:
	idle: iswitchb
switchpulledb:
	idle: iswitchb
		Start: 5
	make: iswitchb
		Length: *
		Tick: 150
switchc:
	idle: iswitchc
switchpulledc:
	idle: iswitchc
		Start: 5
	make: iswitchc
		Length: *
		Tick: 150
switchd:
	idle: iswitchd
switchpulledd:
	idle: iswitchd
		Start: 5
	make: iswitchd
		Length: *
		Tick: 150
        
ibooka:
	idle: ibooks
		Start: 0
ibookb:
	idle: ibooks
		Start: 1
ibookc:
	idle: ibooks
		Start: 2
ibookd:
	idle: ibooks
		Start: 3
ibookdead:
	idle: ibooks
		Start: 4
        
ibannera:
	idle: ibanner
		Start: 0
ibannerb:
	idle: ibanner
		Start: 1
ibannerc:
	idle: ibanner
		Start: 2
ibannerd:
	idle: ibanner
		Start: 3
ibannere:
	idle: ibanner
		Start: 4

objectivea:
	idle: imissionobjective
		Start: 0   
		ZOffset: 102  
objectiveb:
	idle: imissionobjective
		Start: 1  
		ZOffset: 102  
objectivec:
	idle: imissionobjective
		Start: 2  
		ZOffset: 102  
objectived:
	idle: imissionobjective
		Start: 3
		ZOffset: 102  
crackwall:
	idle: 
		ZOffset: 102  
crackwallh:
	idle: 
		ZOffset: 102  
        
        
firepit:
	idle:
	burnloop: burn-m
		Start: 16
		Length: 44
		Tick: 80
		ZOffset: 512
		Offset: 0, -6
        
firetorch:
	idle:
	burnloop: burn-s
		Start: 16
		Length: 44
		Tick: 80
		ZOffset: 512
		Offset: 0, -10
        

firetorchn:
	idle: firetorche
		Start: 0
		ZOffset: 1024
	burnloop: burn-s
		Start: 16
		Length: 44
		Tick: 80
		ZOffset: 1512
		Offset: 0, -5
firetorchnw:
	idle: firetorche
		Start: 1
		ZOffset: 1024
	burnloop: burn-s
		Start: 16
		Length: 44
		Tick: 80
		ZOffset: 1512
		Offset: -6, -8
firetorchw:
	idle: firetorche
		Start: 2
		ZOffset: 1024
	burnloop: burn-s
		Start: 16
		Length: 44
		Tick: 80
		ZOffset: 1512
		Offset: -8, -6
firetorchsw:
	idle: firetorche
		Start: 3
		ZOffset: 1024
	burnloop: burn-s
		Start: 16
		Length: 44
		Tick: 80
		ZOffset: 1512
		Offset: -7, 3
firetorchs:
	idle: firetorche
		Start: 4
		ZOffset: 1024
	burnloop: burn-s
		Start: 16
		Length: 44
		Tick: 80
		ZOffset: 1512
		Offset: 0, 4
firetorchne:
	idle: firetorche
		Start: 7
		ZOffset: 1024
	burnloop: burn-s
		Start: 16
		Length: 44
		Tick: 80
		ZOffset: 1512
		Offset: 6, -8
firetorche:
	idle: firetorche
		Start: 6
		ZOffset: 1024
	burnloop: burn-s
		Start: 16
		Length: 44
		Tick: 80
		ZOffset: 1512
		Offset: 8, -6
firetorchse:
	idle: firetorche
		Start: 5
		ZOffset: 1024
	burnloop: burn-s
		Start: 16
		Length: 44
		Tick: 80
		ZOffset: 1512
		Offset: 7, 3
        
bulb:
	idle: 
		Length: *
		Tick: 200
		BlendMode: DoubleMultiplicative
		UseTilesetCode: false
		-DepthSprite:
		ZRamp: 1 
		ZOffset: -10480 
        
bulbl:
	idle: 
		Length: *
		Tick: 200
		BlendMode: DoubleMultiplicative
		UseTilesetCode: false
		-DepthSprite:
		ZRamp: 1 
		ZOffset: -10480 
bulbr:
	idle: 
		Length: *
		Tick: 200
		BlendMode: DoubleMultiplicative
		UseTilesetCode: false
		-DepthSprite:
		ZRamp: 1 
		ZOffset: -10480 
bulbt:
	idle: 
		Length: *
		Tick: 200
		BlendMode: DoubleMultiplicative
		UseTilesetCode: false
		-DepthSprite:
		ZRamp: 1 
		ZOffset: -10480 
bulbb:
	idle: 
		Length: *
		Tick: 200
		BlendMode: DoubleMultiplicative
		UseTilesetCode: false
		-DepthSprite:
		ZRamp: 1 
		ZOffset: -10480 
bulbtr:
	idle: 
		Length: *
		Tick: 200
		BlendMode: DoubleMultiplicative
		UseTilesetCode: false
		-DepthSprite:
		ZRamp: 1 
		ZOffset: -10480 
bulbtl:
	idle: 
		Length: *
		Tick: 200
		BlendMode: DoubleMultiplicative
		UseTilesetCode: false
		-DepthSprite:
		ZRamp: 1 
		ZOffset: -10480 
bulbbr:
	idle: 
		Length: *
		Tick: 200
		BlendMode: DoubleMultiplicative
		UseTilesetCode: false
		-DepthSprite:
		ZRamp: 1 
		ZOffset: -10480  
bulbbl:
	idle: 
		Length: *
		Tick: 200
		BlendMode: DoubleMultiplicative
		UseTilesetCode: false
		-DepthSprite:
		ZRamp: 1 
		ZOffset: -10480 
        
tsbulbtest:
	idle: 
		BlendMode: DoubleMultiplicative
		UseTilesetCode: false
		-DepthSprite:
		ZRamp: 1
	
treechopped2:
	Defaults:
		UseTilesetExtension: true
		ZOffset: -2024
	make: tree2anim
		Length: *
		Tick: 80
	idle: tree2shop
		Start: 0
	damaged-idle: tree2shop
		Start: 1
	crippled-idle: tree2shop
		Start: 2
	
treechopped3:
	Defaults:
		UseTilesetExtension: true
		ZOffset: -2024
	make: tree3anim
		Length: *
		Tick: 80
	idle: tree3shop
		Start: 0
	damaged-idle: tree3shop
		Start: 1
	crippled-idle: tree3shop
		Start: 2
		
treechopped4:
	Defaults:
		UseTilesetExtension: true
		ZOffset: -2024
	make: tree4anim
		Length: *
		Tick: 80
	idle: tree4shop
		Start: 0
	damaged-idle: tree4shop
		Start: 1
	crippled-idle: tree4shop
		Start: 2

deerstand:
	Defaults:
		Offset: 0,-12
		TilesetOverrides:
			DESERT: TEMPERAT
			WINTER: TEMPERAT
			JUNGLE: TEMPERAT			INTERIOR: TEMPERAT
	idle: 
		Start: 0
	idle2: 
		Start: 1
	corputed1:
		Start: 2
	corputed2:
		Start: 3
	empty: ironore4
		Start: 9 
		
coppermine:
	Defaults:
		Offset: 0,-5
		TilesetOverrides:
			DESERT: TEMPERAT
			INTERIOR: TEMPERAT
	active: cropmin
		Length: *
		Tick: 80
		Start: 0
	idle: cropmin
		Start: 0
		
mwlumbershack:
	Defaults:
		TilesetOverrides:
			DESERT: TEMPERAT
			INTERIOR: TEMPERAT
	idle: mwlumbershack
		Start: 0
		Offset: 0,-12,0
		
ironmine:
	Defaults:
		TilesetOverrides:
			DESERT: TEMPERAT
			INTERIOR: TEMPERAT
	active: iromin
		Length: 29
		Tick: 100
		Start: 1
	idle: iromin
		Start: 0
goldmine:
	Defaults:
		TilesetOverrides:
			DESERT: TEMPERAT
			INTERIOR: TEMPERAT
	active: golmin
		Length: 29
		Tick: 100
		Start: 1
	idle: golmin
		Start: 0

		
mwcamel:
	stand: mwcamel
		Start: 122
		Facings: 8
	run: mwcamel
		Start: 0
		Length: 8
		Facings: 8
		Tick: 100
	shoot: mwcamel
		Tick: 100
		Start: 66
		Length: 7
		Facings: 8
	die1: mwcamel
		Start: 132
		Length: 13
		Tick: 120
	# Burn
	die2: burninghorse
		Start: 76
		Length: 14
		Tick: 80
	idle1: mwcamel
		Tick: 100
		Start: 150
		Length: 7
		Facings: 8
	idle2: mwcamel
		Tick: 500
		Start: 206
		Length: 7
		Facings: 8
		
mwcameltrader:
	stand: 
		Start: 146
		Facings: 8
	run: 
		Start: 0
		Length: 8
		Facings: 8
		Tick: 100
	attack: 
		Start: 65
		Length: 8
		Facings: 8
		Tick: 80
	die1: 
		Start: 156
		Length: 15
		Tick: 80
	# large hit
	die2: splatterdead
		Length: *
		Tick: 80
	# poision
	die3: 
		Start: 187
		Length: 15
		Tick: 80
	# ballista
	die4: 
		Start: 203
		Length: 11
		Tick: 80
	die-crushed: e1rot
		Start: 16
		Length: 4
		Tick: 1600
		ZOffset: -511
	die5: burningman
		Length: *
		Tick: 80
		